### ISSUE TITLE
Feature request: support additional adjustments to bolding method

### ISSUE THREAD

**Issue by Merlin04** [MichaelZhao21/bireader#10]
Bionic Reading has some features which I think could be useful here and not too hard to implement:

- "fixation" - what percent of the word is bolded
- "saccade" - how often to apply the bolding (so 0 would be every word, 1 is every other word, etc)
- "opacity" - the opacity of the bolded text, seems like this could be a useful substitute for font weight if not supported (see below)

Although bionic reading doesn't support this, it also would be nice if it could support adjusting the font weight of the bolding. Maybe this could automatically substitute a variable weight font if the font the text is in doesn't support it? (ideally this behavior would be a configurable parameter)

Great job on this extension by the way, I've already used it a bit and it works really well!

**Comment by Merlin04** [comment]
Actually if you want I'd be happy to work on implementing this and making a PR - just let me know if you'd like me to and I can start working on it

**Comment by MichaelZhao21** [comment]
Yeah, feel free to try adding some of these features! I'm currently a little busy, but I will gladly take a look and suggest changes if you make a pull request.
