### ISSUE TITLE
Ability to control the font-weight of the bold elements

### ISSUE THREAD

**Issue by Ari24-cb24** [MichaelZhao21/bireader#15]
For me personally it's a bit harder to read the text when having font-weight 700. I'd like to have some kind of menu as a popup where one is able to choose from a list of font-weights. May add a pull request sometimes later if I have time but can't promise anything

**Comment by MichaelZhao21** [comment]
Check #11 for the changes that added this option. I still have to resolve a couple of issues regarding the code complexity and moving the UI to the native browser action popup, but you should be able to build the current version from the `master` branch.
